CREATE TABLE usuarios (
	id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	nome VARCHAR(255) NOT NULL,
	userName VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	telefone CHAR(11) NOT NULL,
	senha VARCHAR(255) NOT NULL,
	dataCadastro DATETIME
);